# Archivo de Configuración para el Análisis P2P

# --- Mapeo de Columnas (del CSV de entrada a los nombres esperados por el script) ---
# Descomentar y ajustar si los nombres de las columnas en tu CSV son diferentes.
column_mapping:
  order_number: "Order Number"                 # Identificador único de la orden
  order_type: "Order Type"                   # Tipo de orden (ej. BUY, SELL)
  asset_type: "Asset Type"                   # Criptoactivo (ej. USDT, BTC)
  fiat_type: "Fiat Type"                     # Moneda Fiat (ej. UYU, USD)
  total_price: "Total Price"                 # Monto total en Fiat de la transacción
  price: "Price"                             # Precio unitario del activo en Fiat
  quantity: "Quantity"                       # Cantidad del activo transaccionado
  status: "Status"                           # Estado de la orden (ej. Completed, Cancelled)
  match_time_utc: "Match time(UTC)"            # Fecha y hora de la operación en UTC
  payment_method: "Payment Method"             # Método de pago utilizado
  maker_fee: "Maker Fee"                     # Comisión del Maker (si aplica)
  taker_fee: "Taker Fee"                     # Comisión del Taker (si aplica)
  # Columna opcional para el valor de la venta en una moneda fiat de referencia (ej. USD)
  # Si existe en tu CSV, especifica su nombre aquí.
  # Si no, déjala comentada o vacía.
  # sale_value_reference_fiat: "Value in USD" 

# --- Definición de Operaciones de Venta ---
sell_operation:
  indicator_column: "order_type"  # Columna a usar para identificar ventas (USAR NOMBRE INTERNO)
  indicator_value: "SELL"        # Valor en la columna que indica una venta

# --- Moneda Fiat de Referencia (Opcional) ---
# Si deseas calcular equivalentes de venta en una moneda fiat de referencia (ej. USD)
# y esta no está directamente en las transacciones, puedes definirla aquí.
# El script intentará usar esta moneda si 'sale_value_reference_fiat' no está mapeada arriba
# o si se necesitan conversiones (funcionalidad futura, por ahora es solo una preferencia).
# reference_fiat_for_sales_summary: "USD"

# --- Preferencias del Reporte HTML --- 
# Estas configuraciones definen qué elementos se incluyen por defecto en el reporte HTML generado.
html_report:
  # Tablas a incluir por defecto en el reporte HTML.
  # Especificar las claves de las métricas (como se definen en la función analyze).
  include_tables_default:
    - "asset_stats"
    - "fiat_stats"
    - "price_stats"
    - "fees_stats"
    - "monthly_fiat"
    - "status_counts"
    - "side_counts"
    - "hourly_counts"
    # La tabla 'sales_summary_all_assets_fiat_detailed' se incluye automáticamente si tiene datos.

  # Figuras a incluir en el reporte HTML.
  # Actualmente, el script intenta incluir TODAS las figuras que se generan (o sus placeholders si hay error).
  # Esta lista 'include_figures_default' no se usa activamente para filtrar la selección de figuras en este momento,
  # pero podría usarse en el futuro si se desea un control más granular desde la configuración.
  # Los nombres de archivo aquí son solo ejemplos ilustrativos.
  include_figures_default:
    - "hourly_counts_...png" 
    - "monthly_fiat_volume_...png"
    # - "price_distribution_...png"

  # Opciones para PDF (funcionalidad no implementada actualmente)
  # pdf_generation:
  #   enabled: false
  #   stylesheet: "path/to/custom_stylesheet.css" 